name       : serd
version    : 0.30.4
release    : 4
source     :
    - git|https://github.com/drobilla/serd.git : v0.30.4
license    : ISC
component  : programming.library
summary    : Lightweight RDF parsing library
description: |
    Serd is a lightweight C library for RDF syntax which supports reading and writing Turtle and NTriples.
setup      : |
    %waf_configure --libdir=%libdir%
build      : |
    %waf_build
install    : |
    %waf_install
