name       : serd
version    : 0.30.0
release    : 3
source     :
    - https://github.com/drobilla/serd/archive/v0.30.0.tar.gz : 6d67276c298a60e9eccf00e5fdaff42ced475108b4e1c1f8d71b215578bda93c
license    : ISC
component  : programming.library
summary    : Lightweight RDF parsing library
description: |
    Serd is a lightweight C library for RDF syntax which supports reading and writing Turtle and NTriples.
setup      : |
    ./waf configure --prefix=/usr --libdir=%libdir%
build      : |
    ./waf build
install    : |
    ./waf install --destdir="$installdir"
